In [157]:
import pandas as pd
import numpy as np

In [158]:
country_mapping = pd.read_csv('./120-years-of-olympic-history-athletes-and-results/noc_regions.csv')

In [201]:
country_mapping = country_mapping.drop(['notes'], axis = 1)

In [159]:
total = pd.read_csv('./120-years-of-olympic-history-athletes-and-results/athlete_events.csv')

In [160]:
athlete = total[['ID', 'Name', 'Sex', 'NOC']]

athlete = athlete.drop_duplicates()

In [161]:
athlete['new_ID'] = np.arange(1,len(athlete)+1)

In [162]:
ID_dict = athlete.set_index(['ID','Name','Sex','NOC']).to_dict()['new_ID']
total['new_ID'] = total.apply(lambda x: ID_dict[(x['ID'], x['Name'], x['Sex'], x['NOC'])] ,axis = 1)

In [163]:
game = total[['Year', 'Season', 'City']]

In [164]:
game = game.drop_duplicates()

In [165]:
game['Game_ID'] = np.arange(len(game))

In [166]:
gameID_dict = game.set_index(['Year','Season','City']).to_dict()['Game_ID']

In [167]:
total['Game_ID'] = total.apply(lambda x: gameID_dict[(x['Year'], x['Season'], x['City'])] ,axis = 1)

In [168]:
award = total[['new_ID', 'Game_ID', 'Event', 'Medal']]
award = award[award['Medal'].notnull()]
award = award.drop_duplicates()

In [177]:
award = award[~award[['new_ID', 'Game_ID', 'Event']].duplicated()]

In [173]:
NoAward = total[['new_ID', 'Game_ID', 'Event', 'Medal']]
NoAward = NoAward[NoAward['Medal'].isnull()]

In [174]:
NoAward = NoAward[['new_ID','Game_ID','Event']]
NoAward = NoAward.drop_duplicates()

In [175]:
sport_mapping = total[['Event','Sport']]

In [176]:
sport_mapping = sport_mapping.drop_duplicates()

In [205]:
country_mapping.to_csv("CountryMapping.csv", index = False)
athlete.to_csv("Athlete.csv", index = False)
game.to_csv("Game.csv", index = False)
award.to_csv("Award.csv", index = False)
NoAward.to_csv("NoAward.csv", index = False)
sport_mapping.to_csv("SportMapping.csv", index = False)

In [212]:
athlete[['new_ID','ID','Name','Sex','NOC']].to_csv("Athlete.csv", index = False)
award[['new_ID','Game_ID','Event','Medal']].to_csv("Award.csv", index = False)
country_mapping[['NOC','region']].to_csv("CountryMapping.csv", index = False)
game[['Game_ID','Year','Season','City']].to_csv("Game.csv", index = False)
NoAward[['new_ID','Game_ID','Event']].to_csv("NoAward.csv", index = False)
sport_mapping[['Event','Sport']].to_csv("SportMapping.csv", index = False)

In [214]:
athlete[athlete['NOC'] == 'SIN']

Empty DataFrame
Columns: [ID, Name, Sex, NOC, new_ID]
Index: []

In [213]:
athlete[athlete['NOC'] == 'SGP']

            ID                               Name Sex  NOC  new_ID
578        332                   Zarinah Abdullah   F  SGP     337
2719      1515    Saiyidah Aisyah Mohamed Rafa'ee   F  SGP    1528
7659      4264                     Ang Peng Siong   M  SGP    4296
21961    11575               Lon bin Mohamed Noor   M  SGP   11701
27339    14199         Mei Yen "Christel" Bouvron   F  SGP   14356
33525    17291                        Cai Xiao Li   M  SGP   17487
38075    19565                       Chai Hon Yam   M  SGP   19769
38286    19679            Chan Khun Sing "Joseph"   M  SGP   19886
38291    19682              Kum Seng "Kelly" Chan   M  SGP   19889
38312    19694                  Li Yin "Pat" Chan   F  SGP   19901
38319    19697                 Kum Wah "Roy" Chan   M  SGP   19904
38951    20063               Jung Jun "Mark" Chay   M  SGP   20272
38955    20064                      Chay Weng Yew   M  SGP   20273
39081    20104                        Lionel Chee   M  SGP   20313
39082    20105                      Chee Swee Lee   F  SGP   20314
39250    20186                          Feng Chen   M  SGP   20395
39385    20264                        Chen Sho Fa   M  SGP   20474
39574    20361                Xinru "Colin" Cheng   M  SGP   20572
41011    21132                Bei Fen Jovina Choo   F  SGP   21356
41425    21369                    Chua Koon Siong   M  SGP   21594
41428    21371                     Chua Phung Kim   M  SGP   21597
41674    21486                     Ch`ng Seng Mok   M  SGP   21718
44376    22885                 James Bryden Cooke   M  SGP   23123
45581    23520             Burdett Matthew Coutts   M  SGP   23758
49134    25303      Yvonne Margaret Danson (-Tan)   F  SGP   25552
51796    26613             Osbert John de Rozario   M  SGP   26870
54438    27921                Vellupillai Devadas   M  SGP   28184
57518    29466         Edwin Jeyaceilan Doraisamy   M  SGP   29743
60185    30818                Thomas Kevin Durcan   M  SGP   31110
67722    34619                      Feng Tian Wei   F  SGP   34956
...        ...                                ...  ..  ...     ...
256621  128496                        Wang Jue Gu   F  SGP  130063
258052  129221                      Wee Tian Siak   M  SGP  130794
262587  131391  Alexander Nicolaas "Skip" Wolters   M  SGP  132985
262588  131392                Wiebe Johan Wolters   M  SGP  132986
262651  131420              Zi Liang "Derek" Wong   M  SGP  133014
262657  131424              Kar Mun "Helena" Wong   F  SGP  133018
262659  131426             Wong Liang Hun "James"   M  SGP  133020
262677  131432                       Wong Kay Poh   M  SGP  133026
262679  131434                       Wong Kim Poh   M  SGP  133028
262708  131448                      Wong Yew Tong   M  SGP  133042
263236  131718              Michael George Wright   M  SGP  133312
263854  132037                        Xing Aiying   F  SGP  133631
263990  132101                       Xu Yuan Zhen   M  SGP  133695
264965  132579                            Yang Zi   M  SGP  134176
265039  132626                            Yao Lei   F  SGP  134223
265054  132637             Jin Wei "Timothee" Yap   M  SGP  134234
265272  132757                       Yee Tit Kwan   M  SGP  134355
265469  132850                 Oon Tat "Eric" Yeo   M  SGP  134454
265471  132852                  Foo Ee "Gary" Yeo   M  SGP  134456
265472  132853                       Yeo Gek Huat   M  SGP  134457
265494  132855            Wei Ling "Joscelin" Yeo   F  SGP  134459
265513  132856               Wi Jin "Kenneth" Yeo   M  SGP  134460
265517  132857                      Yeo Kian Chye   M  SGP  134461
265777  132986            Yin Yue "Elizabeth" Yin   F  SGP  134597
265972  133071              Pei Lin "Audrey" Yong   F  SGP  134682
266550  133346                          Yu Mengyu   F  SGP  134957
268673  134414                          Zhan Jian   M  SGP  136057
268752  134454                      Zhang Guirong   F  SGP  136097
268993  134587                      Zhang Xueling   F  SGP  136230
269455  134826                         Zhou Yihan   F  SGP  136474

[172 rows x 5 columns]

In [209]:
country_mapping.head()

   NOC       region
0  AFG  Afghanistan
1  AHO      Curacao
2  ALB      Albania
3  ALG      Algeria
4  AND      Andorra

In [216]:
country_mapping[country_mapping['NOC'] == 'SIN']

     NOC     region
178  SIN  Singapore